[services.go-gateway]
path = "./scrapers"
command = "go"
args = ["run", "cmd/api/main.go"]

[services.scala-gateway]
path = "./ingestion"
command = "sbt"
args = ["run"]

[services.intelligence]
path = "./backend"
command = "python"
args = ["-m", "uvicorn", "main:app", "--reload", "--port", "8000"]

[services.interface]
path = "./frontend"
command = "npm"
args = ["run", "dev"]
