// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: scrapper.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScrapperService_StreamScrapeData_FullMethodName = "/scrapper.ScrapperService/StreamScrapeData"
)

// ScrapperServiceClient is the client API for ScrapperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScrapperServiceClient interface {
	// Client-side streaming of scraped data to the Scala backend
	StreamScrapeData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ScrapePayload, ScrapeResponse], error)
}

type scrapperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScrapperServiceClient(cc grpc.ClientConnInterface) ScrapperServiceClient {
	return &scrapperServiceClient{cc}
}

func (c *scrapperServiceClient) StreamScrapeData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ScrapePayload, ScrapeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ScrapperService_ServiceDesc.Streams[0], ScrapperService_StreamScrapeData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScrapePayload, ScrapeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScrapperService_StreamScrapeDataClient = grpc.ClientStreamingClient[ScrapePayload, ScrapeResponse]

// ScrapperServiceServer is the server API for ScrapperService service.
// All implementations must embed UnimplementedScrapperServiceServer
// for forward compatibility.
type ScrapperServiceServer interface {
	// Client-side streaming of scraped data to the Scala backend
	StreamScrapeData(grpc.ClientStreamingServer[ScrapePayload, ScrapeResponse]) error
	mustEmbedUnimplementedScrapperServiceServer()
}

// UnimplementedScrapperServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScrapperServiceServer struct{}

func (UnimplementedScrapperServiceServer) StreamScrapeData(grpc.ClientStreamingServer[ScrapePayload, ScrapeResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamScrapeData not implemented")
}
func (UnimplementedScrapperServiceServer) mustEmbedUnimplementedScrapperServiceServer() {}
func (UnimplementedScrapperServiceServer) testEmbeddedByValue()                         {}

// UnsafeScrapperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScrapperServiceServer will
// result in compilation errors.
type UnsafeScrapperServiceServer interface {
	mustEmbedUnimplementedScrapperServiceServer()
}

func RegisterScrapperServiceServer(s grpc.ServiceRegistrar, srv ScrapperServiceServer) {
	// If the following call panics, it indicates UnimplementedScrapperServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScrapperService_ServiceDesc, srv)
}

func _ScrapperService_StreamScrapeData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ScrapperServiceServer).StreamScrapeData(&grpc.GenericServerStream[ScrapePayload, ScrapeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScrapperService_StreamScrapeDataServer = grpc.ClientStreamingServer[ScrapePayload, ScrapeResponse]

// ScrapperService_ServiceDesc is the grpc.ServiceDesc for ScrapperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScrapperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scrapper.ScrapperService",
	HandlerType: (*ScrapperServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamScrapeData",
			Handler:       _ScrapperService_StreamScrapeData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "scrapper.proto",
}
