// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: scrapper.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScrapePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceUrl     string                 `protobuf:"bytes,1,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	DomainEntity  string                 `protobuf:"bytes,2,opt,name=domain_entity,json=domainEntity,proto3" json:"domain_entity,omitempty"` // e.g., "Supplier", "News"
	RawContent    string                 `protobuf:"bytes,3,opt,name=raw_content,json=rawContent,proto3" json:"raw_content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapePayload) Reset() {
	*x = ScrapePayload{}
	mi := &file_scrapper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapePayload) ProtoMessage() {}

func (x *ScrapePayload) ProtoReflect() protoreflect.Message {
	mi := &file_scrapper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapePayload.ProtoReflect.Descriptor instead.
func (*ScrapePayload) Descriptor() ([]byte, []int) {
	return file_scrapper_proto_rawDescGZIP(), []int{0}
}

func (x *ScrapePayload) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *ScrapePayload) GetDomainEntity() string {
	if x != nil {
		return x.DomainEntity
	}
	return ""
}

func (x *ScrapePayload) GetRawContent() string {
	if x != nil {
		return x.RawContent
	}
	return ""
}

func (x *ScrapePayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ScrapePayload) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ScrapeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ProcessedCount int32                  `protobuf:"varint,3,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScrapeResponse) Reset() {
	*x = ScrapeResponse{}
	mi := &file_scrapper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeResponse) ProtoMessage() {}

func (x *ScrapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scrapper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeResponse.ProtoReflect.Descriptor instead.
func (*ScrapeResponse) Descriptor() ([]byte, []int) {
	return file_scrapper_proto_rawDescGZIP(), []int{1}
}

func (x *ScrapeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScrapeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ScrapeResponse) GetProcessedCount() int32 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

var File_scrapper_proto protoreflect.FileDescriptor

const file_scrapper_proto_rawDesc = "" +
	"\n" +
	"\x0escrapper.proto\x12\bscrapper\"\x92\x02\n" +
	"\rScrapePayload\x12\x1d\n" +
	"\n" +
	"source_url\x18\x01 \x01(\tR\tsourceUrl\x12#\n" +
	"\rdomain_entity\x18\x02 \x01(\tR\fdomainEntity\x12\x1f\n" +
	"\vraw_content\x18\x03 \x01(\tR\n" +
	"rawContent\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12A\n" +
	"\bmetadata\x18\x05 \x03(\v2%.scrapper.ScrapePayload.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\x0eScrapeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fprocessed_count\x18\x03 \x01(\x05R\x0eprocessedCount2Z\n" +
	"\x0fScrapperService\x12G\n" +
	"\x10StreamScrapeData\x12\x17.scrapper.ScrapePayload\x1a\x18.scrapper.ScrapeResponse(\x01B&Z$github.com/jaxcode23/scrapers/pkg/pbb\x06proto3"

var (
	file_scrapper_proto_rawDescOnce sync.Once
	file_scrapper_proto_rawDescData []byte
)

func file_scrapper_proto_rawDescGZIP() []byte {
	file_scrapper_proto_rawDescOnce.Do(func() {
		file_scrapper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scrapper_proto_rawDesc), len(file_scrapper_proto_rawDesc)))
	})
	return file_scrapper_proto_rawDescData
}

var file_scrapper_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_scrapper_proto_goTypes = []any{
	(*ScrapePayload)(nil),  // 0: scrapper.ScrapePayload
	(*ScrapeResponse)(nil), // 1: scrapper.ScrapeResponse
	nil,                    // 2: scrapper.ScrapePayload.MetadataEntry
}
var file_scrapper_proto_depIdxs = []int32{
	2, // 0: scrapper.ScrapePayload.metadata:type_name -> scrapper.ScrapePayload.MetadataEntry
	0, // 1: scrapper.ScrapperService.StreamScrapeData:input_type -> scrapper.ScrapePayload
	1, // 2: scrapper.ScrapperService.StreamScrapeData:output_type -> scrapper.ScrapeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_scrapper_proto_init() }
func file_scrapper_proto_init() {
	if File_scrapper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scrapper_proto_rawDesc), len(file_scrapper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scrapper_proto_goTypes,
		DependencyIndexes: file_scrapper_proto_depIdxs,
		MessageInfos:      file_scrapper_proto_msgTypes,
	}.Build()
	File_scrapper_proto = out.File
	file_scrapper_proto_goTypes = nil
	file_scrapper_proto_depIdxs = nil
}
