akka {
  loglevel = "INFO"
  http {
    server {
      preview.enable-http2 = on
    }
  }
}

riskintel {
  ingestion {

    broker-url = "localhost:9092"
    topics = ["global-news", "logistics-events"]
  }
}
